// vue/src/App.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted, onUnmounted } from "vue";

type Todo = { id: string; title: string; completed: boolean };

const storageKey = "todomvc";

const editedTodoId = ref<string>();
const editedTodoMemo = ref("");
const todos = ref<Todo[]>(JSON.parse(localStorage.getItem(storageKey) ?? "[]"))
const filteredType = ref<"all" | "completed" | "active">("all");
const filteredTodos = computed(() => {
    return filteredType.value === "all" ? [...todos.value]
        : filteredType.value === "completed" ? todos.value.filter(todo => todo.completed)
            : filteredType.value === "active" ? todos.value.filter(todo => !todo.completed)
                : [];
});
const activeCount = computed(() => todos.value.filter(todo => !todo.completed).length)

watch(todos, value => {
    localStorage.setItem(storageKey, JSON.stringify(value))
}, { flush: "sync", deep: true });

onMounted(() => globalThis.addEventListener("hashchange", handleHashChange));
onUnmounted(() => globalThis.removeEventListener("hashchange", handleHashChange));

function addTodo(event: KeyboardEvent) {
    const target = event.target as HTMLInputElement

    if (!target.value) return;

    todos.value.push({ id: String(Date.now()), title: target.value.trim(), completed: false });
    target.value = "";
}

function toggleAll() {
    activeCount.value === 0
        ? todos.value.forEach(todo => todo.completed = false)
        : todos.value.forEach(todo => todo.completed = true)
}

function handleHashChange() {
    const route = globalThis.location.hash.replace(/#\/?/, "");

    if (route === "all" || route === "active" || route === "completed") {
        filteredType.value = route;
        return;
    }

    globalThis.location.hash = "";
    filteredType.value = "all";
}

function handleVnodeMounted({ el }: { el: HTMLInputElement }) {
    el.focus();
}
</script>

<template>
    <section class="todoapp">
        <header class="header">
            <h1>todos</h1>
            <input class="new-todo" autofocus placeholder="What needs to be done?" @keyup.enter="addTodo" />
        </header>
        <section class="main" v-show="filteredTodos.length">
            <input id="toggle-all" class="toggle-all" type="checkbox" :checked="activeCount === 0" @change="toggleAll" />
            <label for="toggle-all">Mark all as complete</label>
            <ul class="todo-list">
                <li v-for="todo in filteredTodos" class="todo" :key="todo.id"
                    :class="{ completed: todo.completed, editing: editedTodoId === todo.id }">
                    <div class="view">
                        <input class="toggle" type="checkbox" v-model="todo.completed" />
                        <label @dblclick="editedTodoId = todo.id, editedTodoMemo = todo.title">{{ todo.title }}</label>
                        <button class="destroy"
                            @click="todos.splice(todos.findIndex(item => item.id === todo.id), 1)"></button>
                    </div>
                    <input v-if="todo.id === editedTodoId" class="edit" type="text" v-model="todo.title"
                        @blur="editedTodoId = undefined" @keyup.enter="editedTodoId = undefined"
                        @vnode-mounted="handleVnodeMounted"
                        @keyup.escape="editedTodoId = undefined, todos.find(item => item.id === todo.id && (item.title = editedTodoMemo))" />
                </li>
            </ul>
        </section>
        <footer class="footer" v-show="todos.length">
            <span class="todo-count">
                <strong>{{ activeCount }}</strong>
                <span>{{ activeCount === 1 ? ' item' : ' items' }} left</span>
            </span>
            <ul class="filters">
                <li><a href="#/all" :class="{ selected: filteredType === 'all' }">All</a></li>
                <li><a href="#/active" :class="{ selected: filteredType === 'active' }">Active</a></li>
                <li><a href="#/completed" :class="{ selected: filteredType === 'completed' }">Completed</a></li>
            </ul>
            <button class="clear-completed" @click="todos = todos.filter(todo => !todo.completed)" v-show="activeCount < todos.length">
                Clear completed
            </button>
        </footer>
    </section>
</template>

// react/src/App.tsx
import { useState, useEffect, useMemo, KeyboardEvent, FocusEvent } from "react";

type Todo = { id: string; title: string; completed: boolean };

const storageKey = "todomvc";

function App() {
    const [todos, setTodos] = useState<Todo[]>(JSON.parse(localStorage.getItem(storageKey) ?? "[]"));
    const [filterType, setFilterType] = useState<"all" | "active" | "completed">("all");
    const [editingId, setEditingId] = useState<string>();

    const activeCount = useMemo(() => todos.filter(todo => !todo.completed).length, [todos])
    const filteredTodos = useMemo(() => {
        if (filterType === "all") return [...todos];
        if (filterType === "active") return todos.filter(todo => !todo.completed);
        if (filterType === "completed") return todos.filter(todo => todo.completed);

        return [];
    }, [todos, filterType]);

    useEffect(() => localStorage.setItem(storageKey, JSON.stringify(todos)), [todos]);
    useEffect(() => {
        globalThis.addEventListener("hashchange", handleHashChange);
        return () => globalThis.removeEventListener("hashchange", handleHashChange);
    });

    return (
        <section className="todoapp">
            <header className="header">
                <h1>todos</h1>
                <input className="new-todo" autoFocus placeholder="What needs to be done?" onKeyUp={addTodo} />
            </header>
            {Boolean(filteredTodos.length) && <section className="main">
                <input id="toggle-all" className="toggle-all" type="checkbox" checked={activeCount === 0} onChange={toggleAll} />
                <label htmlFor="toggle-all">Mark all as complete</label>
                <ul className="todo-list">{filteredTodos.map(todo =>
                    <li className={["todo", todo.completed ? "completed" : "", editingId === todo.id ? "editing" : ""].join(" ")} key={todo.id}>
                        <div className="view">
                            <input className="toggle" type="checkbox" checked={todo.completed} onChange={() => toggleTodo(todo.id)} />
                            <label onDoubleClick={() => setEditingId(todo.id)}>{todo.title}</label>
                            <button className="destroy" onClick={() => removeTodo(todo.id)}></button>
                        </div>{editingId === todo.id &&
                            <input className="edit" type="text" defaultValue={todo.title} onBlur={handleBlurEvent} onKeyUp={handleKeyupEvent}
                                ref={ref => Promise.resolve().then(() => ref?.focus())} />
                        }</li>)}
                </ul>
            </section>}{Boolean(todos.length) && <footer className="footer">
                <span className="todo-count">
                    <strong>{activeCount}</strong>
                    <span> item{activeCount > 1 && "s"} left</span>
                </span>
                <ul className="filters">
                    <li><a href="#/all" className={filterType === "all" ? "selected" : ""}>All</a></li>
                    <li><a href="#/active" className={filterType === "active" ? "selected" : ""}>Active</a></li>
                    <li><a href="#/completed" className={filterType === "completed" ? "selected" : ""}>Completed</a></li>
                </ul>
                {activeCount < todos.length && <button className="clear-completed" onClick={clearCompletedTodo}>Clear completed</button>}
            </footer>}
        </section>
    );

    function addTodo({ key, target }: KeyboardEvent) {
        if (key.toLowerCase() !== "enter") return;
        if (!target) return

        const input = target as HTMLInputElement;

        if (!input.value) return

        setTodos([...todos, { id: String(Date.now()), title: input.value, completed: false }])
        input.value = "";
    }

    function toggleAll() {
        setTodos(todos.map(todo => ({ ...todo, completed: activeCount !== 0 })));
    }

    function toggleTodo(id: string) {
        setTodos(todos.map(todo => todo.id === id ? { ...todo, completed: !todo.completed } : todo))
    }

    function removeTodo(id: string) {
        setTodos(todos.filter(todo => todo.id !== id))
    }

    function handleBlurEvent({ target }: FocusEvent<HTMLInputElement>) {
        const input = target as HTMLInputElement;
        const index = todos.findIndex(todo => todo.id === editingId);

        if (index === -1) return;

        todos[index].title = input.value;
        setTodos(todos)
        setEditingId(undefined);
    }

    function handleKeyupEvent({ key, target }: KeyboardEvent) {
        const input = target as HTMLInputElement;

        if (key.toLowerCase() === "enter") {
            input.blur();
            return;
        }

        if (key.toLowerCase() === "escape") {
            input.value = todos.find(todo => todo.id === editingId)?.title ?? input.value;
            input.blur();
            return;
        }
    }

    function clearCompletedTodo() {
        setTodos(todos.filter(todo => !todo.completed));
    }

    function handleHashChange() {
        const route = globalThis.location.hash.replace(/#\/?/, "");

        if (route === "all" || route === "active" || route === "completed") {
            setFilterType(route)
            return;
        }

        globalThis.location.hash = "";
        setFilterType("all");
    }
}

export default App
