// src/App.vue
<script setup lang="ts">
import { ref, reactive, computed, watch } from "vue";

type Todo = {
    uuid: number;
    name: string;
    editable: boolean;
    complete: boolean;
};

const storageKey = "vue-todomvc";
const input = ref("");
const todos = reactive<Todo[]>(JSON.parse(localStorage.getItem(storageKey) ?? "[]"));
const filteredType = ref<"all" | "complete" | "incomplete">("all");
const filteredTodos = computed(() => {
    if (filteredType.value === "all") return todos;
    if (filteredType.value === "complete") return todos.filter(todo => todo.complete);
    if (filteredType.value === "incomplete") return todos.filter(todo => !todo.complete);
});
const isAllCompleted = computed(() => !Boolean(todos.find(todo => !todo.complete)))

watch(todos, value => localStorage.setItem(storageKey, JSON.stringify(value)));

function addTodo() {
    if (!input.value) return;

    const todo: Todo = {
        uuid: Date.now(),
        name: input.value.trim(),
        complete: false,
        editable: false,
    };

    todos.push(todo);
    input.value = "";
}

function updateTodoName(event: InputEvent, todo: Todo) {
    const input = event.target as HTMLInputElement;
    const value = input.value;

    todo.name = value;
}
</script>

<template>
    <main>
        <section><input v-model="input" @keyup.enter="addTodo" placeholder="What needs to be done?" />
        </section>
        <section>
            <div v-for="todo in filteredTodos" :key="todo.uuid">
                <input type="checkbox" v-model="todo.complete" />
                <span @dblclick="todo.editable = !todo.editable">
                    <input :value="todo.name" :disabled="!todo.editable" @blur="todo.editable = false"
                        @input="(event: InputEvent) => updateTodoName(event, todo)" />
                </span>
                <button @click="todos.splice(todos.indexOf(todo), 1)">delete</button>
            </div>
        </section>
        <section>
            <button
                @click="isAllCompleted ? todos.forEach(todo => todo.complete = false) : todos.forEach(todo => todo.complete = true)">
                Toggle
            </button>
            <select v-model="filteredType">
                <option value="all">All</option>
                <option value="complete">Completed</option>
                <option value="incomplete">Incompleted</option>
            </select>
        </section>
    </main>
</template>

// solid/src/App.tsx
import { For, createRenderEffect, createMemo, createSignal } from "solid-js";
import { createStore } from "solid-js/store"

type Todo = {
    uuid: number;
    name: string;
    editable: boolean;
    complete: boolean;
};
type FilteredType = "all" | "complete" | "incomplete";

function App() {
    let inputRef: HTMLInputElement | undefined;
    const storageKey = "solid-todomvc";
    const [todos, setTodos] = createStore<Todo[]>(JSON.parse(localStorage.getItem(storageKey) ?? "[]"));
    const [getFilteredType, setFilteredType] = createSignal<FilteredType>("all");
    const filteredTodos = createMemo(() => {
        const type = getFilteredType();

        if (type === "all") return todos;
        if (type === "complete") return todos.filter(todo => todo.complete);
        if (type === "incomplete") return todos.filter(todo => !todo.complete);

        return [];
    });

    createRenderEffect(() => {
        localStorage.setItem(storageKey, JSON.stringify(todos));
    });

    return (
        <main>
            <section><input ref={inputRef} onKeyUp={addTodo} placeholder="What needs to be done?" /></section>
            <section><ol>
                <For each={filteredTodos()}>{
                    todo => <li>
                        <input type="checkbox" checked={todo.complete}
                            onChange={e => setTodos(todos.findIndex(item => item.uuid === todo.uuid), "complete", e.target.checked)}
                        />
                        <span ondblclick={() => setTodos(todos.findIndex(item => item.uuid === todo.uuid), "editable", true)}>
                            <input disabled={!todo.editable} value={todo.name}
                                onBlur={() => setTodos(todos.findIndex(item => item.uuid === todo.uuid), "editable", false)}
                                onChange={e => setTodos(todos.findIndex(item => item.uuid === todo.uuid), "name", e.target.value)}
                            />
                        </span>
                        <button onClick={() => setTodos(todos => todos.filter(item => item.uuid !== todo.uuid))}>delete</button>
                    </li>
                }</For></ol>
            </section>
            <section>
                <button onClick={toggleAll}>toggle</button>
                <select onChange={e => setFilteredType(e.target.value as FilteredType)}>
                    <option value="all">all</option>
                    <option value="complete">completed</option>
                    <option value="incomplete">incompleted</option>
                </select>
            </section>
        </main>
    )

    function addTodo(event: KeyboardEvent) {
        if (event.key.toLowerCase() !== "enter") return;
        if (!inputRef?.value) return;

        const todo: Todo = {
            uuid: Date.now(),
            name: inputRef.value,
            editable: false,
            complete: false,
        };

        inputRef.value = "";
        setTodos(todos => [...todos, todo]);
    }

    function toggleAll() {
        const isAllCompleted = !todos.some(todo => !todo.complete);

        setTodos({ from: 0, to: todos.length - 1 }, "complete", !isAllCompleted);
    }
}

export default App
